# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
import numpy as np
arr = np.zeros(10,)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [8]:
import numpy as np
arr = np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [10]:
import numpy as np
p = np.array([5,5,5,5,5,5,5,5,5,5])
print(p)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [ ]:
import numpy as np
p = np.arange(10,51)
print(p)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### Create an array of all the even integers from 10 to 50

In [37]:
import numpy as np
arr = np.linspace(10,51,dtype=int)
print(arr)
arrr = arr[arr%2==0]
print(arrr)

[10 10 11 12 13 14 15 15 16 17 18 19 20 20 21 22 23 24 25 25 26 27 28 29
 30 30 31 32 33 34 35 35 36 37 38 39 40 40 41 42 43 44 45 45 46 47 48 49
 50 51]
[10 10 12 14 16 18 20 20 22 24 26 28 30 30 32 34 36 38 40 40 42 44 46 48
 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [2]:
import numpy as np
n =np.array([[0,1,2],[3,4,5],[6,7,8]])
print(n)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [39]:
import numpy as np
arr = np.eye(3,3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [42]:
import random
arr = random.randint(0,1)
print(arr)

0


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [44]:
import random
arr = np.random.randn(25)
print(arr)

[ 0.21597169 -1.10241049 -0.65799378 -1.58200499  1.212789   -0.95986023
  0.12719155 -0.18184365  0.48509799 -0.04665524 -2.17964392  1.25636342
  1.89766164  0.13686493  0.39377185  1.02066289  0.10260742 -0.76617895
 -0.58283356  1.87103904 -0.9430922   0.9548667  -1.55885802 -0.79208012
  0.74017266]


#### Create the following matrix:

In [7]:
import numpy as np
arr = np.arange(1,101,dtype=float)
print(arr)

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.
  15.  16.  17.  18.  19.  20.  21.  22.  23.  24.  25.  26.  27.  28.
  29.  30.  31.  32.  33.  34.  35.  36.  37.  38.  39.  40.  41.  42.
  43.  44.  45.  46.  47.  48.  49.  50.  51.  52.  53.  54.  55.  56.
  57.  58.  59.  60.  61.  62.  63.  64.  65.  66.  67.  68.  69.  70.
  71.  72.  73.  74.  75.  76.  77.  78.  79.  80.  81.  82.  83.  84.
  85.  86.  87.  88.  89.  90.  91.  92.  93.  94.  95.  96.  97.  98.
  99. 100.]


#### Create an array of 20 linearly spaced points between 0 and 1:

In [72]:
import numpy as np
arr = np.linspace(0,1,20,dtype=float)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [73]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [39]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [81]:
print(arr[-3:])

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [29]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [86]:
print(arr[3,4])

20


In [30]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

array([[ 2],
       [ 7],
       [12]])

In [31]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [89]:
print(arr[4])

[21 22 23 24 25]


In [32]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [91]:
np.array(arr[-2:])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [64]:
import numpy as np
import random 
arr = np.arange(26)

print(arr)
sum = arr.sum()
print(sum)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25]
325


#### Get the standard deviation of the values in mat

In [67]:
import numpy as np
arr = np.std([1,2,3,4,5,6,24])
print(arr)

7.345691504104251


#### Get the sum of all the columns in mat

In [54]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
sum = arr.sum(axis=2)
print(sum)

[[ 6 15 24]]


import numpy as np
arr = np.array([[1, 2, 3, 4]
                 [5, 6, 7, 8]
                 [9, 10, 11, 12]]
a. Retrieve the element at the second row and third column. 
b. Slice the subarray containing the first two rows and the last two columns. 
c. Calculate the sum of each column in the array.)

In [20]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr[1,3])
p = np.array(arr[:2])
n= np.array(arr[:,-2:])
print(p)
print(n)
sum = arr.sum(axis=1)
print(sum)

 

8
[[1 2 3 4]
 [5 6 7 8]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[10 26 42]


Generate a 3x3 matrix of random integers between 1 and 100. Calculate the mean and standard deviation of the matrix.

In [ ]:
import numpy as np
arr = np.array([[[1,2,3],[]]])
np.me

[]


Create a NumPy array with 100 random integers between 1 and 50. Find and print the elements that are greater than 30.

In [1]:

import numpy as np
arr = np.random.randint(1, 51, 100)
greater = arr[arr > 30]

print(arr)
print("\nElements greater than 30:\n", greater)


[49 27  5 41 46 46 43  1  4 16 47 50 14 23 14 50 34 17  2 25 23 31  7  7
 14 15 44 35 31 33 15 42  5 33 21  2  2 12  7 28 21  3 31  8 22  8  3 35
  6 44  5 48  5 26  6 16 10  4 30 17 10 12 22 23 34 10 19 22 27  3 36 11
 37  8  1 49  4 16 47 33  6 48 34 46 38 31 15 11 12 19 33 36 31 46 18  8
 12 37  3 17]

Elements greater than 30:
 [49 41 46 46 43 47 50 50 34 31 44 35 31 33 42 33 31 35 44 48 34 36 37 49
 47 33 48 34 46 38 31 33 36 31 46 37]


A = np.array([[1, 2, 3],              
              [4, 5, 6],
              [7, 8, 9]])
B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
a. Compute the matrix multiplication of A and B. 
b. Calculate the determinant of matrix A. 
c. Find the eigenvalues and eigenvectors of matrix B.

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])
mult = np.dot(A,B)
print(mult)
determ= np.linalg.det(A)
print(determ)
eig= np.linalg.eig(B)
print(eig)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
0.0
EigResult(eigenvalues=array([ 1.61168440e+01, -1.11684397e+00, -5.03850873e-16]), eigenvectors=array([[-0.8186735 , -0.61232756,  0.40824829],
       [-0.52532209,  0.08675134, -0.81649658],
       [-0.23197069,  0.78583024,  0.40824829]]))


Certainly! Here are a few NumPy-related questions of varying difficulty levels: 
 
Question 1: Array Operations 
 
Create a NumPy array arr with elements from 1 to 10 (inclusive). Perform the following operations: 
 
a. Square each element of the array. 
b. Calculate the mean of the squared array. 
c. Reshape the array to a 2x5 matrix.

Create a NumPy array with values ranging from 1 to 10.  
  
Create a 3x3 matrix with values ranging from 0 to 8.  
  
Create a 2x2 identity matrix.  
  
Generate a random 4x4 matrix and find the minimum and maximum values in it.  
  
Create a 5x5 matrix with values 1, 2, 3, 4 just below the main diagonal.  
  
Given a 1D array, negate all elements that are between 3 and 8, in place.  
  
Create a 2D array of shape (5, 5) with decimal numbers and round each element to the nearest integer.  
  
Create a random 5x5 matrix and normalize it by subtracting the mean and dividing by the standard deviation along each row. 
Generate a 1D array of 10 equally spaced values between 0 and 1, inclusive.